# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(choices=[('unknown', 'Unknown'), ('house', 'House'), ('tech_house', 'Tech House'), ('deep_house', 'Deep House')], default='unknown', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('release_date', models.DateTimeField()),
                ('is_purchasable', models.BooleanField(default=False)),
                ('is_available_for_mix', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title of track')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='tracks.Genre')),
            ],
        ),
    ]
